// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformaBranzowaTI.DAL;

#nullable disable

namespace PlatformaBranzowaTI.Migrations
{
    [DbContext(typeof(SensorsContext))]
    [Migration("20251216104743_Dane")]
    partial class Dane
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlatformaBranzowaTI.Models.SensorReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Humidity")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SensorReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Humidity = 45.200000000000003,
                            Notes = "Normalna praca",
                            Temperature = 21.5,
                            Timestamp = new DateTime(2025, 12, 16, 6, 57, 43, 68, DateTimeKind.Local).AddTicks(3606)
                        },
                        new
                        {
                            Id = 2,
                            Humidity = 44.799999999999997,
                            Notes = "Stabilne warunki",
                            Temperature = 21.699999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 7, 7, 43, 68, DateTimeKind.Local).AddTicks(3721)
                        },
                        new
                        {
                            Id = 3,
                            Humidity = 44.100000000000001,
                            Temperature = 22.0,
                            Timestamp = new DateTime(2025, 12, 16, 7, 17, 43, 68, DateTimeKind.Local).AddTicks(3735)
                        },
                        new
                        {
                            Id = 4,
                            Humidity = 43.899999999999999,
                            Notes = "Lekki wzrost temperatury",
                            Temperature = 22.300000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 7, 27, 43, 68, DateTimeKind.Local).AddTicks(3747)
                        },
                        new
                        {
                            Id = 5,
                            Humidity = 43.5,
                            Temperature = 22.100000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 7, 37, 43, 68, DateTimeKind.Local).AddTicks(3757)
                        },
                        new
                        {
                            Id = 6,
                            Humidity = 43.0,
                            Temperature = 21.899999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 7, 47, 43, 68, DateTimeKind.Local).AddTicks(3780)
                        },
                        new
                        {
                            Id = 7,
                            Humidity = 42.799999999999997,
                            Notes = "Spadek wilgotności",
                            Temperature = 21.600000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 7, 57, 43, 68, DateTimeKind.Local).AddTicks(3792)
                        },
                        new
                        {
                            Id = 8,
                            Humidity = 42.5,
                            Temperature = 21.399999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 8, 7, 43, 68, DateTimeKind.Local).AddTicks(3804)
                        },
                        new
                        {
                            Id = 9,
                            Humidity = 42.0,
                            Temperature = 21.199999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 8, 17, 43, 68, DateTimeKind.Local).AddTicks(3815)
                        },
                        new
                        {
                            Id = 10,
                            Humidity = 41.799999999999997,
                            Notes = "Stabilizacja",
                            Temperature = 21.0,
                            Timestamp = new DateTime(2025, 12, 16, 8, 27, 43, 68, DateTimeKind.Local).AddTicks(3831)
                        },
                        new
                        {
                            Id = 11,
                            Humidity = 41.5,
                            Temperature = 20.899999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 8, 37, 43, 68, DateTimeKind.Local).AddTicks(3842)
                        },
                        new
                        {
                            Id = 12,
                            Humidity = 41.200000000000003,
                            Temperature = 20.800000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 8, 47, 43, 68, DateTimeKind.Local).AddTicks(3855)
                        },
                        new
                        {
                            Id = 13,
                            Humidity = 41.0,
                            Notes = "Warunki optymalne",
                            Temperature = 20.699999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 8, 57, 43, 68, DateTimeKind.Local).AddTicks(3866)
                        },
                        new
                        {
                            Id = 14,
                            Humidity = 40.799999999999997,
                            Temperature = 20.899999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 9, 7, 43, 68, DateTimeKind.Local).AddTicks(3877)
                        },
                        new
                        {
                            Id = 15,
                            Humidity = 40.5,
                            Temperature = 21.100000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 9, 17, 43, 68, DateTimeKind.Local).AddTicks(3889)
                        },
                        new
                        {
                            Id = 16,
                            Humidity = 40.200000000000003,
                            Notes = "Wzrost temperatury",
                            Temperature = 21.399999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 9, 27, 43, 68, DateTimeKind.Local).AddTicks(3900)
                        },
                        new
                        {
                            Id = 17,
                            Humidity = 40.0,
                            Temperature = 21.800000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 9, 37, 43, 68, DateTimeKind.Local).AddTicks(3910)
                        },
                        new
                        {
                            Id = 18,
                            Humidity = 39.799999999999997,
                            Temperature = 22.199999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 9, 47, 43, 68, DateTimeKind.Local).AddTicks(3927)
                        },
                        new
                        {
                            Id = 19,
                            Humidity = 39.5,
                            Notes = "Cieplej niż zwykle",
                            Temperature = 22.5,
                            Timestamp = new DateTime(2025, 12, 16, 9, 57, 43, 68, DateTimeKind.Local).AddTicks(3940)
                        },
                        new
                        {
                            Id = 20,
                            Humidity = 39.200000000000003,
                            Temperature = 22.800000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 10, 7, 43, 68, DateTimeKind.Local).AddTicks(3951)
                        },
                        new
                        {
                            Id = 21,
                            Humidity = 39.0,
                            Temperature = 23.0,
                            Timestamp = new DateTime(2025, 12, 16, 10, 17, 43, 68, DateTimeKind.Local).AddTicks(3962)
                        },
                        new
                        {
                            Id = 22,
                            Humidity = 38.700000000000003,
                            Notes = "Niska wilgotność",
                            Temperature = 23.199999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 10, 27, 43, 68, DateTimeKind.Local).AddTicks(3973)
                        },
                        new
                        {
                            Id = 23,
                            Humidity = 38.5,
                            Temperature = 23.399999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 10, 37, 43, 68, DateTimeKind.Local).AddTicks(3984)
                        },
                        new
                        {
                            Id = 24,
                            Humidity = 38.299999999999997,
                            Temperature = 23.600000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 10, 47, 43, 68, DateTimeKind.Local).AddTicks(3998)
                        },
                        new
                        {
                            Id = 25,
                            Humidity = 38.0,
                            Notes = "Zbliża się próg ostrzegawczy",
                            Temperature = 23.800000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 10, 57, 43, 68, DateTimeKind.Local).AddTicks(4009)
                        },
                        new
                        {
                            Id = 26,
                            Humidity = 37.799999999999997,
                            Temperature = 24.0,
                            Timestamp = new DateTime(2025, 12, 16, 11, 7, 43, 68, DateTimeKind.Local).AddTicks(4020)
                        },
                        new
                        {
                            Id = 27,
                            Humidity = 37.5,
                            Temperature = 24.199999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 11, 17, 43, 68, DateTimeKind.Local).AddTicks(4031)
                        },
                        new
                        {
                            Id = 28,
                            Humidity = 37.200000000000003,
                            Notes = "Wysoka temperatura",
                            Temperature = 24.399999999999999,
                            Timestamp = new DateTime(2025, 12, 16, 11, 27, 43, 68, DateTimeKind.Local).AddTicks(4042)
                        },
                        new
                        {
                            Id = 29,
                            Humidity = 37.0,
                            Temperature = 24.600000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 11, 37, 43, 68, DateTimeKind.Local).AddTicks(4052)
                        },
                        new
                        {
                            Id = 30,
                            Humidity = 36.799999999999997,
                            Notes = "Ostatni odczyt",
                            Temperature = 24.800000000000001,
                            Timestamp = new DateTime(2025, 12, 16, 11, 47, 43, 68, DateTimeKind.Local).AddTicks(4064)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
